name: workflows 的名称
on:
  push:
    branches:
      - test

jobs:
  my-job:
    name: job 名称
    runs-on: macos-latest
    steps:
      - name: 步骤名称
        env:
          MY_VAR: 设置的变量
          VAR_1: 变量 1
        run: |
          echo "echo start"
          whoami
          tree
          whoami
          echo "echo end"

