name: workflows 的名称
on:
  push:
    branches:
      - test

jobs:
  my-job:
    name: job 名称
    runs-on: macos-latest
    steps:
      - name: echo start
        run: echo "echo start"
      - name: whoami
        run: whoami
      - name: tree
        run: tree
      - name: echo end
        run: echo "echo end"

