name: workflows 的名称
on:
  push:
  branches:
    - master

jobs:
  my-job:
    name: job 名称
    runs-on: ubuntu-latest
    steps:
      - name: 步骤名称
        env:
          MY_VAR: 设置的变量
          VAR_1: 变量 1
        run: echo $MY_VAR $VAR_1.