name: workflows 的名称
on:
  push:
    branches:
      - test

jobs:
  my-job:
    name: job 名称
    runs-on: macos-latest
    steps:
      - name: echo start
        run: echo "echo start"
      - name: whoami
        run: whoami && sleep 10s
      - name: tree
        run: tree
      - name: echo end
        run: echo "echo end"
      - name: always
        if: always()
        run: echo "echo always"
      - name: success
        if: success()
        run: echo "echo success"
      - name: failure
        if: failure()
        run: echo "echo failure"
      - name: cancelled
        if: cancelled()
        run: echo "echo cancelled"

